on:
  push:
    branches:
      - main

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Execute remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.SSH_USERNAME }}/domains/development-agt.web.id/public_html/penjualan-tenant
            git fetch origin main
            git reset --hard origin/main
            git clean -fd
            composer install --no-interaction --prefer-dist --optimize-autoloader --ignore-platform-reqs --no-scripts
            php artisan package:discover --ansi
            php artisan vendor:publish --tag=filament-assets --force
            php artisan vendor:publish --tag=filament-forms-assets --force
            php artisan vendor:publish --tag=filament-tables-assets --force
            php artisan filament:assets
            php artisan optimize:clear